title: Mind Palace
description: Deterministic context for AI agents
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

search_enabled: true
aux_links:
  "GitHub Repository": https://github.com/koksalmehmet/mind-palace
