title: Mind Palace
description: Deterministic context for AI agents
remote_theme: pmarsceill/just-the-docs

# Visuals
color_scheme: dark
callouts_level: quiet

# UX Features
search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

# Footer
footer_content: "Copyright &copy; 2025 Mind Palace"

# External
aux_links:
  "CLI Repository": https://github.com/koksalmehmet/mind-palace
  "Extension Repository": https://github.com/koksalmehmet/mind-palace-vscode

# Navigation order is controlled by nav_order in front matter
